repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.262
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/pre-commit/mirrors-yapf.git
    rev: v0.30.0
    hooks:
    - id: yapf
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    - id: isort
      args:
      - --filter-files
      additional_dependencies: [types-requests]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: end-of-file-fixer
        exclude: (?x)(
          .*\.faa$|
          .*\.pdb$
          )
    -   id: trailing-whitespace
        exclude: (?x)(
          .*\.faa$|
          .*\.pdb$
          )
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject
        # Optional extra validations from SchemaStore:
        additional_dependencies: ["validate-pyproject-schema-store[all]"]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.2.0
  #   hooks:
  #   -   id: mypy
  #       args: [--no-strict-optional, --ignore-missing-imports]
  #       exclude: (docs|tests)
